### ISSUE TITLE
Integration error

### ISSUE THREAD

**Issue by LumingSun** [Nathaniel-Han/End-to-End-CardEst-Benchmark#4]
Great work!

I followed the instructions and set the knobs for join(multi-table) as true and use the estimated result from DeepDB with:
```
SET ml_joinest_enabled=true; 
SET join_est_no=0; 
SET ml_joinest_fname='stats_CEB_sub_queries_deepdb.txt'; 
```
then I run the first sub-query in the repo, but I got the following error:
```
stats=# explain analyse SELECT * FROM users as u, badges as b WHERE b.UserId= u.Id AND u.UpVotes>=0;
server closed the connection unexpectedly
	This probably means the server terminated abnormally
	before or while processing the request.
The connection to the server was lost. Attempting reset: Failed.
```
Is there anything that I missed? And is it possible to only set knobs for join as true while leaving single-table estimation using the default PG estimations?

**Comment by Nathaniel-Han** [comment]
Hi Luming, 
Thanks for your interest in our benchmark. 
As for your first question, please check if `stats_CEB_sub_queries_deepdb.txt` is in your $PSQL_DATA_DIRECTORY. Otherwise, Postgres can't find this file.
And the answer to your second question is YES. Actually, only setting `ml_joinest_enabled`, `join_est_no` and `ml_joinest_fname` will do this trick. However, if you also set `ml_cardest_enabled`, `query_no` and `ml_cardest_fname`, then our benchmark will also read estimates of single tables from the injected file.

**Comment by LumingSun** [comment]
Thank you for your reply!

I found the problem that I copyed the [multi-table method].txt to ```/var/lib/pgsql/13.1/data```, but also ```set ml_cardest_enabled=true``` by mistake while didn't provide a sing-table method.txt.
I recreated a container and use the only sub-query related set command, and it is OK now.
